import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Script from "next/script";
import "./globals.css";

import Footer from "../components/Footer";
import Header from "../components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          {/* Inline BangDB Script */}
          <Script
            id="bangdb-init"
            strategy="beforeInteractive"
            dangerouslySetInnerHTML={{
              __html: `
                var _paq = (window._paq = window._paq || []);
                _paq.push(['enableLinkTracking'], ['enableHeartBeatTimer', 30], ['trackAllContentImpressions']);
                var _mtm = (window._mtm = window._mtm || []);
                _mtm.push({'mtm.startTime': (new Date().getTime()), 'event': 'mtm.Start'});
                (function () {
                  var u = 'https://s-bugcheckyopmailcombasvmrjfy.bangdb.com:18080/stream/testBug/testbug';
                  _paq.push(['setTrackerUrl', u], ['setSiteId', 'invoice']);
                })();
              `,
            }}
          />
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen grid grid-rows-[auto_1fr_auto]`}
        >
          <Header />
          {children}
          <Footer />
          {/* External BangDB Scripts */}
          <Script
            src="https://cdn.bangdb.com/tm/RYF1QYPFRXEP/matomo.js"
            strategy="lazyOnload"
          />
          <Script
            src="https://cdn.bangdb.com/tm/RYF1QYPFRXEP/0d11343227924f0cb932105714baa74f/mastercontainer.js"
            strategy="lazyOnload"
          />
        </body>
      </html>
    </ClerkProvider>
  );
}
